"use client";
import type { getUserAnalytics } from "@/server/analytics/report";
import { Metric, Panel, bytes, date, time } from "./dashboard";
export function UserProfile({ data }: {
    data: NonNullable<ReturnType<typeof getUserAnalytics>>;
}) {
    const { user, activity, books, totals, timeline } = data;
    const abandoned = books.filter(b => b.status === "reading" && b.last_opened_at && Date.parse(b.last_opened_at) < Date.parse(data.generatedAt) - 30 * 86400000).length;
    return <><div className="an-page-heading"><div><div className="an-eyebrow">READER PROFILE</div><h1>{user.display_name || user.email}</h1><p>{user.email} · {user.role} · {user.email_verified_at ? "Verified account" : "Awaiting verification"}</p><p>User ID: {user.id}</p></div></div><div className="an-metrics"><Metric label="Joined" value={date(user.created_at)}/><Metric label="Last meaningful activity" value={date(activity?.last_activity)}/><Metric label="Books owned" value={books.length}/><Metric label="Storage used" value={bytes(books.reduce((n, b) => n + b.bytes, 0))}/><Metric label="Currently reading" value={books.filter(b => b.status === "reading").length}/><Metric label="Books completed" value={books.filter(b => b.status === "finished").length}/><Metric label="Potentially abandoned" value={abandoned} note="Reading, no access for more than 30 days"/><Metric label="Product sessions" value={totals.sessions} note="since tracking began"/><Metric label="Reading sessions" value={totals.reading_sessions}/><Metric label="Reading time" value={time(totals.seconds)}/><Metric label="Observed PDF page advances" value={totals.pages}/><Metric label="Last reading activity" value={date(activity?.last_read_at)}/></div><Panel title="Library" note={`Last book opened: ${books.find(b => b.last_opened_at)?.title ?? "Not observed"}`}><div className="an-table-wrap"><table><thead><tr><th>Book</th><th>Status</th><th>Progress</th><th>Storage</th><th>Last opened</th></tr></thead><tbody>{books.map(b => <tr key={b.id}><td>{b.title}</td><td>{b.status}</td><td>{b.progress}%</td><td>{bytes(b.bytes)}</td><td>{date(b.last_opened_at)}</td></tr>)}</tbody></table>{!books.length && <p className="an-empty">This user has no books.</p>}</div></Panel><Panel title="Activity timeline" note="Latest 100 milestones in the last 180 days. Reading totals are aggregated, not emitted for each page."><div className="an-timeline">{timeline.map(e => <div key={e.id}><b>{e.kind.replaceAll("_", " ")}</b>{e.label && ` · ${e.label}`}<small>{new Date(e.at).toLocaleString("en", { timeZone: "UTC" })} UTC</small></div>)}{!timeline.length && <p className="an-empty">No observed events yet.</p>}</div></Panel></>;
}
