/* eslint-disable @typescript-eslint/no-require-imports */
/* Isolated SQLite integration tests; TypeScript is compiled with the project's own compiler. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'shelf-analytics-test-'));
process.env.SHELF_DATA_DIR = directory;
process.env.SHELF_REQUIRE_EMAIL_VERIFICATION = 'false';
process.env.SHELF_SESSION_SECRET = 'isolated-test-secret-with-at-least-32-characters';
const RealDate = Date;
let clock = RealDate.parse('2026-01-01T12:00:00.000Z');
global.Date = class extends RealDate { constructor(...args) { super(...(args.length ? args : [clock])); } static now() { return clock; } };
let token;
const originalLoad = Module._load;
Module._load = function(id, parent, isMain) {
  if (id === 'server-only') return {};
  if (id === 'next/headers') return { headers: async () => new Headers(), cookies: async () => ({ get: () => token ? { value: token } : undefined }) };
  if (id.startsWith('@/')) id = path.join(process.cwd(), 'src', id.slice(2));
  return originalLoad.call(this, id, parent, isMain);
};
Module._extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText, filename);
const { getDb, MIGRATIONS } = require('../src/server/db.ts');
const { recordActivity, readingPulse } = require('../src/server/analytics/tracking.ts');
const { getAnalytics, getUserAnalytics } = require('../src/server/analytics/report.ts');
const { createUser, createSession } = require('../src/server/auth.ts');
const { books } = require('../src/server/repo.ts');
const { GET } = require('../src/app/api/admin/analytics/route.ts');
const { POST } = require('../src/app/api/analytics/route.ts');
const db = getDb();
const scalar = sql => Object.values(db.prepare(sql).get())[0];
async function run() {
  assert.equal(scalar('SELECT COUNT(*) FROM schema_migrations'), MIGRATIONS.length, 'additive migration applied');
  db.prepare("UPDATE analytics_meta SET value=? WHERE key='started_at'").run('2026-01-01T00:00:00.000Z');
  const empty=getAnalytics({start:'2026-01-01',end:'2026-01-01',bucket:'day',active:7,inactive:30,dormant:90});
  assert.equal(empty.totals.users,0);
  assert.equal(empty.current.active,0);
  assert.equal(empty.cohorts.length,0);
  const admin = await createUser('admin@example.test', 'test-password-123', 'Admin');
  db.prepare("UPDATE users SET role='admin' WHERE id=?").run(admin.id);
  const user = await createUser('reader@example.test', 'test-password-123', 'Reader');
  assert.equal(scalar('SELECT COUNT(*) FROM analytics_daily_users'), 0, 'registration alone is not meaningful engagement');
  recordActivity(admin.id, 'login');
  const book = books.create(user.id, { format:'pdf', title:'Test Book', author:'Author', description:'', category:'Other', tags:[], status:'want-to-read', totalPages:100, fileName:'test.pdf', fileSize:1000, coverKind:'none', coverSize:20 });
  const first = readingPulse(user.id, book.id, 1, undefined, 1);
  assert.ok(first.sessionId);
  assert.equal(readingPulse(user.id, book.id, 1, undefined, 1).sessionId, first.sessionId, 'double mount coalesced');
  assert.equal(scalar('SELECT SUM(reading_sessions) FROM analytics_daily_users'), 1);
  clock += 30000;
  readingPulse(user.id, book.id, 2, first.sessionId, 2);
  assert.equal(scalar('SELECT SUM(reading_seconds) FROM analytics_daily_users'), 30);
  assert.equal(scalar('SELECT SUM(pages) FROM analytics_daily_users'), 1);
  clock += 10000;
  readingPulse(user.id, book.id, 2, first.sessionId, 2);
  assert.equal(scalar('SELECT SUM(reading_seconds) FROM analytics_daily_users'), 30, 'duplicate sequence is idempotent');
  assert.equal(readingPulse(admin.id, book.id, 2), null, 'ownership enforced');
  db.prepare('UPDATE analytics_users SET reading_seen=NULL WHERE user_id=?').run(user.id);
  clock += 180000;
  const resumed=readingPulse(user.id,book.id,3,first.sessionId,3);
  assert.notEqual(resumed.sessionId,first.sessionId);
  assert.equal(scalar('SELECT SUM(reading_seconds) FROM analytics_daily_users'),30,'hidden pause time excluded');
  clock += 30000;
  readingPulse(user.id,book.id,80,resumed.sessionId,4);
  assert.equal(scalar('SELECT SUM(pages) FROM analytics_daily_users'),1,'page jumps do not inflate pages');
  assert.ok(db.prepare('SELECT return_read FROM analytics_users WHERE user_id=?').get(user.id).return_read);
  assert.equal(readingPulse(user.id,book.id,3,first.sessionId,5).stale,true,'superseded tabs rejected');
  const epub=books.create(user.id,{format:'epub',title:'EPUB',author:'',description:'',category:'Other',tags:[],status:'reading',totalPages:1000,fileName:'test.epub',fileSize:500,coverKind:'none',coverSize:0});
  const ep=readingPulse(user.id,epub.id,1,undefined,1);clock+=30000;readingPulse(user.id,epub.id,2,ep.sessionId,2);
  assert.equal(scalar('SELECT SUM(pages) FROM analytics_daily_users'),1,'EPUB locations are not PDF pages');
  assert.equal(scalar('SELECT SUM(locations) FROM analytics_daily_users'),1);
  clock=RealDate.parse('2026-01-02T12:00:00Z');recordActivity(user.id,'library_opened');
  clock=RealDate.parse('2026-01-08T12:00:00Z');recordActivity(user.id,'library_opened');books.update(user.id,book.id,{status:'finished'});
  clock=RealDate.parse('2026-04-15T12:00:00Z');
  const filter={start:'2026-01-01',end:'2026-04-15',bucket:'week',active:7,inactive:30,dormant:90};
  const report=getAnalytics(filter);
  assert.equal(report.totals.bytes,1520);
  assert.equal(report.current.pages,1);
  assert.equal(report.segments.find(s=>s.name==='Dormant').users,2);
  assert.equal(report.cohorts[0].days.find(d=>d.offset===1).retained,1);
  assert.equal(report.cohorts[0].days.find(d=>d.offset===7).eligible,2);
  assert.equal(report.cohorts[0].days.find(d=>d.offset===7).retained,1);
  assert.equal(report.cohorts[0].days.find(d=>d.offset===30).retained,0);
  assert.equal(report.series.find(p=>p.day==='2025-12-29').active,2,'weekly active is distinct, not sum of DAU');
  assert.equal(report.funnel[0].users,2);
  assert.equal(report.funnel.at(-1).users,1);
  assert.ok(report.totals.completionDays>6);
  const before=getAnalytics({...filter,start:'2025-12-01',end:'2025-12-02',bucket:'day'});
  assert.equal(before.series[0].seconds,null,'pre-instrumentation chart values are unavailable');
  assert.equal(before.series[0].storage,null,'missing storage snapshots remain gaps');
  const mature=getAnalytics({...filter,start:'2026-01-01',end:'2026-01-01',bucket:'day'});
  assert.ok(mature.series.length===1);
  // Authorization and validation against real route handlers.
  token=undefined;
  assert.equal((await GET(new Request('http://localhost/api/admin/analytics'))).status,401);
  token=(await createSession(user.id)).token;
  assert.equal((await GET(new Request('http://localhost/api/admin/analytics'))).status,403);
  const tracking=(body,origin='http://localhost')=>POST(new Request('http://localhost/api/analytics',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)}));
  assert.equal((await tracking({kind:'library_opened'},'https://attacker.test')).status,403);
  assert.equal((await tracking({kind:'reading',bookId:'not-owned',page:1,sequence:1})).status,404);
  token=(await createSession(admin.id)).token;
  assert.equal((await GET(new Request('http://localhost/api/admin/analytics?start=2026-02-30'))).status,400);
  assert.equal((await GET(new Request('http://localhost/api/admin/analytics?active=100&inactive=30'))).status,400);
  const response=await GET(new Request('http://localhost/api/admin/analytics'));
  assert.equal(response.status,200);
  assert.match(response.headers.get('cache-control'),/no-store/);
  const payload=await response.json();assert.ok(!JSON.stringify(payload).includes('password_hash'));
  assert.ok(getUserAnalytics(user.id).timeline.length);
  books.remove(user.id,book.id);
  assert.equal(scalar('SELECT COUNT(*) FROM analytics_book_state'),1,'deleted book facts cascade');
  assert.equal(scalar('SELECT SUM(removed_bytes) FROM analytics_storage_daily'),1020);
  assert.equal(getAnalytics(filter).totals.bytes,500);
  assert.equal(scalar('SELECT SUM(reading_seconds) FROM analytics_daily_users'),90,'user reading totals survive book removal');
  db.prepare("INSERT INTO users(id,email,password_hash,created_at,updated_at) VALUES ('legacy','legacy@example.test','unused','2020-01-01T00:00:00Z','2020-01-01T00:00:00Z')").run();
  assert.equal(getAnalytics(filter).segments.find(s=>s.name==='Unobserved').users,1,'old unobserved accounts are not assumed dormant');
  const boundary = (days) => { db.prepare('UPDATE analytics_users SET last_activity=? WHERE user_id=?').run(new Date(clock-days*86400000).toISOString(),user.id);return getAnalytics(filter).users.find(u=>u.id===user.id).segment; };
  assert.equal(boundary(7),'Active');assert.equal(boundary(8),'Recently inactive');assert.equal(boundary(30),'Recently inactive');assert.equal(boundary(31),'Inactive');assert.equal(boundary(90),'Inactive');assert.equal(boundary(91),'Dormant');
  clock=RealDate.parse('2026-01-01T23:59:00Z');
  const immature=getAnalytics({...filter,end:'2026-01-01'});
  assert.equal(immature.cohorts[0].days[0].eligible,0,'same-day cohorts have no mature day-one retention');
  console.log('Analytics integration checks passed: migrations, ownership, auth, validation, session deduplication, idle time, page semantics, cohorts, funnels, distinct actives, storage, deletion, and history gaps.');
}
run().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{db.close();fs.rmSync(directory,{recursive:true,force:true});global.Date=RealDate;});
